dataset: data/dataset.fasta
groundtruth: data/cigars_truth.txt
sets_number: 20
dpus_number: 10

nw_params:
  match: 2
  mismatch: -4
  gap_opening: 4 #0 for linear
  gap_extension: 2
  width: 128 # always 128 for dpu
